spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
      hibernate.search.default.directory_provider: filesystem
      hibernate.search.default.indexBase: target/lucenefiles
      hibernate.search.lucene_version: LUCENE_CURRENT
      hibernate.search.model_mapping: ca.uhn.fhir.jpa.search.LuceneSearchMappingFactory
  jackson:
    default-property-inclusion: non_null

  h2:
    console:
      enabled: true
      path: /h2-console
  application:
    name: foo

#hapi:
#  fhir:
#    version: dstu3
#    server:
#      path: /fhir/*
#    rest:
#      server-name: cms-bb-poc
#      server-version: 1.0.0
#      implementation-description: Juice Labs CMS Blue Button POC
#      default-response-encoding: json
#      e-tag-support: enabled
#      default-pretty-print: true
#    validation:
#      enabled: true
#      request-only: true
#    jpa:
#      scheduling-disabled: true
#      subscription-enabled: false
management:
  security:
    enabled: false
